### PR TITLE
Logo alignment fixes

### LINKED ISSUE #392: Site Title doesn't line up with BYU Logo
# Description
Site Title doesn't line up with BYU Logo. Instead the BYU logo sits a little below it.

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
The alignment should be like this, with the capital letters aligned with the BYU logo, and ascenders potentially going higher:

image

Instead it looks like this: 
image

# Websites Affected
All. For example, lifesciences.byu.edu

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
# Summary of Changes

**Fixes #392 **

Also includes an adjustment to the fallback styles that makes the logo get positioned more reliably.

# Browser Testing

**I have tested these changes in:**

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

### CODE REVIEW

**Comment by Gi60s** [comment]
On both Firefox and Chrome in Linux the title currently appears to be half a pixel to high.

**Comment by ThatJoeMoore** [comment]
*sigh*.  Why in the world are we using half-pixel heights?

**Comment by Gi60s** [comment]
I agree. Why are we?

**Comment by ThatJoeMoore** [comment]
Because some people don't believe that anyone uses anything besides Mac?

**Comment by ThatJoeMoore** [comment]
Can you tell if it would be better to round it to 18px or 19 px?

**Comment by Gi60s** [comment]
It's certainly closer now. I think the BYU logo image size may not be to an exact pixel.

**Comment by ThatJoeMoore** [comment]
Yeah, we may want to review that image in the future, especially since we keep having issues with it.  I wouldn't be surprised if it's not aligned properly.

**Pull request merged**
