### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
Contains fixes to the following issues:

* #250 - More Menu Arrow Animation
* #261 - Menu Background
* #269 - More menu arrow missing in IE11
* #271 - Nav bar fixed with - - extra color on either end
* #272 - Footer link font size
* #274 - Main index.html issue
* #276 - Extra Margins with p tag: Edge

# Testing

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

### CODE REVIEW

**Comment by ThatJoeMoore** [comment]
We can live with the non-responsive footer in Safari for now.  Safari, being Safari, refuses to give me the info I need to fix it, so let's just deal with it for now.  It really only affects us developers, as most people don't resize their browsers often (especially on a phone, where you can't).

**Comment by bmorgan296** [comment]
Sounds good! Then assuming the footer pattern is correct, LGTM!

**Comment by ThatJoeMoore** [comment]
I'm working on the footer padding now.  It looks like a leftover bug from my changes in 1.1.0

**Comment by ThatJoeMoore** [comment]
Okay, I've got fixes in for the footer padding issues.

**Comment by bmorgan296** [comment]
:shipit:

**Comment by ThatJoeMoore** [comment]
Alright.  Here goes nothing.

**Pull request merged**
