### PR TITLE
added constrain attribute to the byu-header tag

### PR DESCRIPTION
**Pull request by tombates6**
# Summary of Changes

**Fixes Issue #(Add issue number here)**

*What did you change? If this is a bug fix, how did you fix it?*

**If this fixes styling, please include before and after screenshots!**

# Browser Testing

**I have tested these changes in:**

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

### CODE REVIEW

**Comment by blakemorgan** [comment]
Nice work! Just a few things:

1. When you constrain the width, the "BYU" monogram need to line up with the edge of the menu. It looks like it is too far in.

Screen Shot 2020-12-21 at 8 23 53 AM

2. Your FOUS styles on the right side of the page only work when there is a `byu-search` component. The styles have to be able to work regardless of the components on the page.
3. The documentation needs to be update to reflect the new functionality (in the `docs` folder).
4. You need to test it with different browser sizes (smallest size 320px) as well. You can do that using browser dev tools. It looks like you're also constraining mobile (which shouldn't be happening).

**Review by blakemorgan — CHANGES_REQUESTED** [review]
See above comment.

**Comment by tombates6** [comment]
Rebecca Bean said I should be doing this with flexbox and CSS grid instead of hard coding numbers. I get why I would want to do that, but I don't know how to work with those tools yet. Should I spend some time learning it so I can apply it, or should I stick with this solution?

**Comment by blakemorgan** [comment]
@tombates6 Nice work with the desktop stuff! Looks like you just got to do mobile and update the docs, then you should be good to go with the constrained header.

**Comment by blakemorgan** [comment]
You've done something that shrinks the header's vertical height on mobile and it no longer matches brand.byu.edu.

Screen Shot 2020-12-29 at 10 04 07 AM

**Comment by tombates6** [comment]
@blakemorgan I think this fixes the problem above. ☝🏼

**Comment by blakemorgan** [comment]
The mobile issue is fixed, but you need to reduce the space of the sides before reducing the distance between each side of the header (like it does on brand.byu.edu).

**Comment by blakemorgan** [comment]
Superseded by #498

**Pull request closed without merging**
