### PR TITLE
Safari Mobile Search (Fixes #298)

### LINKED ISSUE #298: [byu-search] Search doesn't disappear in iOS Safari
# Description

*Tell us all about your problem or feature proposal.*

The search does not disappear when the menu is expanded in iOS Safari.

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
[asb-ucom-dev2.byu.edu](asb-ucom-dev2.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

### PR DESCRIPTION
**Pull request by bmorgan296**
# Summary of Changes

**Fixes Issue #298**

I added the `menu-open` attribute to the parent div of `byu-header-search` and added JavaScript to work with that element in addition to the `byu-header` element.

**If this fixes styling, please include before and after screenshots!**

# Browser Testing

**I have tested these changes in:**

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

### CODE REVIEW

**Comment by ThatJoeMoore** [comment]
Could you explain what the root problem you found was?

I'm hesitant to merge this much new javascript without understand what the root problem was.

**Comment by bmorgan296** [comment]
The root problem was that `byu-header-search` wasn't recognizing the `menu-open` attribute which was on the `byu-header` tag. Therefore the transition would not be triggered. So I copied that attribute to the div containing `byu-header-search` and then it recognized the attribute.

**Comment by ThatJoeMoore** [comment]
It seems to me, then, that we have a problem with our CSS structure, not where the attributes are being placed.

**Comment by bmorgan296** [comment]
I tried moving it to the bottom of `byu-header.scss` and `byu-header-extras.scss` and the didn't solve the problem. I also tried giving all the properties in `searchTransition` and `searchTransformed` the `!important` attribute. None of those solved the issue.

**Comment by kebowdog** [comment]
I've done some additional testing and found that Safari thinks it's applying the css, it's just.... not. Looking at it in Web Inspector gives the following:
image

At this point I vote we either 1) just approve Blake's changes for now and check back after the next iOS update to see if it's still an issue or 2) Just ignore it as an edge case and hope future versions of iOS fix their shadow dom implementation.

**Comment by bmorgan296** [comment]
WE decided to spend more time finding the root of this problem. We will be fixing it via CSS, not this JS hack.

**Pull request closed without merging**
