### PR TITLE
Release 1.2.1

### LINKED ISSUE #303: [byu-footer] Left/Right Footer Margin
# Description

This is another quetsion for @Aleniras: Is the padding supposed to be that small between the edge of the browser and the gray footer? I know it seems like no one would noticed this because they won't be resizing their browser, but if they're like me and sometimes have their browser this width, they may notice it.
screen shot 2017-08-19 at 3 16 49 pm

# Websites Affected

- [asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)
- [photo-dev2.byu.edu](https://photo-dev2.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [x] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

### LINKED ISSUE #321: Remove font call in menu - causing duplicate billing to Hoeffler
# Description
A reference to the fonts is still included in byu-menu.html.
This means that if someone includes the different font package, we are being billed twice/it is counting twice and adding up. This is very likely why we hit and passed our plan limit for the Hoeffler fonts recently.
I have checked that this font reference isn't needed. Kevin also has confirmed it.
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

image

# Websites Affected
Homepage (was affected, we took it out in our own), speeches.byu.edu, Calendar.byu.edu and any other website that is referencing the Full font package and the components.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
Contains the following changes:

* #316 byu-search doesn't find input on slotchange
* #319 Footer Padding Fix (fixes #303)
* #322 Remove erroneous font file load (fixes #321 )
* #323 add `constrain-top-bar` to byu-header

# Testing

## Sites Running `experimental/release-1.2.1`
* [typo-dev.byu.edu](http://typo-dev.byu.edu)

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

### CODE REVIEW

**Comment by ThatJoeMoore** [comment]
This is ready for review.  I unfortunately don't have much time to help with the testing.

**Comment by ThatJoeMoore** [comment]
Note: There are more changes that were merged than are listed in the release notes, but they were all backed out.

**Comment by bmorgan296** [comment]
Functionality is fine. The only issues I see are with specs:
- Plain footer text is wrong color
- Footer hover text is wrong color

Do we want to fix those for this release or just put them on the next one?

**Comment by bmorgan296** [comment]
Blue footer text is wrong color in Firefox and IE11
capture

**Pull request merged**
