### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by bmorgan296**
Contains fixes to the following issues:
- #158: Updated mobile menu search display/animation
- #283: Added ability to specify selector for active state
- #284: Flex menu link
- #285: Full width header and content width menu
- #287: Document release process and timeline
- #288: Add sticky footer documentation
- #293: Long title too close to menu button
- #297: More menu display
- #298: Mobile search disappearing in iOS

# Testing

## Sites Running `experimental/release-1.2.0`
- [asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

### CODE REVIEW

**Comment by bmorgan296** [comment]
Found UI bug in Firefox. Opened #297.

**Comment by bmorgan296** [comment]
Found mobile search error in iOS Safari. Opened #298.

**Comment by bmorgan296** [comment]
Found possible UI error. Waiting for response from @Aleniras. Opened #306.

**Comment by bmorgan296** [comment]
The class is getting loaded for the mobile search to disappear, but it still isn't disappearing.

**Comment by kebowdog** [comment]
@bmorgan296 I've just tested it on my iPad at http://2017-components-demo.cdn.byu.edu/?branch=release-1.2.0 and it's disappearing just fine. Can you and/or @ThatJoeMoore check again?

**Pull request merged**
