### PR TITLE
Mobile search

### PR DESCRIPTION
**Pull request by rburkey87**
# Summary of Changes
Added CSS transition to remove search bar when mobile menu is opened. Search bar re-appears when mobile menu is closed.

When reviewing, please test with the branch so you can see (and approve the animation). It's not totally ideal, but it's about as good as I've been able to get it.

**Fixes Issue #158**

## BEFORE
**Menu closed**
image

**Menu open**
image

## AFTER
**Menu closed**
image

**Menu open**
image

# Browser Testing

**I have tested these changes in:**

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

### CODE REVIEW

**Comment by kebowdog** [comment]
It's working, though I'm also not thrilled with how the animation ends up looking. Maybe at tomorrow's meeting we could look at other options?

**Comment by ThatJoeMoore** [comment]
Yeah, I'm pretty sure we're not going to find an elegant way to hide the search bar. @rburkey87 has tried a lot of different options, and none of them really look good. I'm thinking it would be best to implement something like http://admissions.byu.edu , and just move where the expansion of the menu happens to be above the search bar.  I know that's not what Aleni wants, but unless she can describe an elegant way to hide it, I'm not sure there's a good solution to be found.

Personally, I don't see the problem with keeping the search bar around when the menu is expanded.  In fact, many leading sites only show the search bar when the menu is showing, or after the user taps on a search icon.  See (in order of Alexa ranking) YouTube, Reddit, Wikipedia, Twitter, or the prettiest option, Apple.

**Comment by bmorgan296** [comment]
At then engineering meeting on 7/11/17, we reviewed the different animations as a committee and decided to discuss with @Aleniras what some alternatives may be. I am replacing the 1.1.1 tag with 1.1.2 to give us time to talk with the design group.

**Comment by rburkey87** [comment]
The layout has been altered to push the search bar below the mobile menu, as Aleni requested if it couldn't disappear. However, this branch is currently set to make the search bar transition into not displaying as it's pushed down by the mobile menu. There are concerns expressed about performance with two animations. Will someone review it?

**Comment by bmorgan296** [comment]
The animation looks great. But one more issue on iOS: the padding between the title and menu button is pretty small. I don't know if we want to fix that or if that is intentional.
img_0104

**Comment by ThatJoeMoore** [comment]
Yeah, we should probably fix that, but let's do it as a separate issue.

**Pull request merged**
